import {listObjects,listAttachments,saveBundle,readMeta,writeMeta,listMeta,saveMeta} from './store.js';
const $ = selector => document.querySelector(selector);
const el = (tag, cls, text) => {const node=document.createElement(tag); if(cls)node.className=cls; if(text!==undefined)node.textContent=text; return node;};
let objects=[],attachments=[],selectedId=null,dirty=false,mode='board',shown=[],camera={x:30,y:30,scale:1},urls=[],timer,installPrompt,lastId,busy=false;
const board=$('#board'),world=$('#world'),form=$('#edit-form');
const item = id => objects.find(object=>object.id===id);
const active = () => objects.filter(object=>!object.archived);
const safeUrl = value => {try{const url=new URL(value); return ['http:','https:'].includes(url.protocol)?url.href:null;}catch{return null;}};
const relationIds = object => [...new Set([...(object.relationships||[]),...active().filter(other=>(other.relationships||[]).includes(object.id)).map(other=>other.id)])].filter(id=>item(id)&&!item(id).archived&&id!==object.id);
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,4500);}
function keepUrl(blob){const url=URL.createObjectURL(blob);urls.push(url);return url;}
function normalize(object,index=0){return {...object,content:object.content||'',url:object.url||'',tags:object.tags||[],attachmentIds:object.attachmentIds||[],relationships:object.relationships||[],position:object.layoutVersion===2?object.position:{x:30+(index%3)*290,y:30+Math.floor(index/3)*245},layoutVersion:2};}
function newObject(title,type,index=active().length){return normalize({id:crypto.randomUUID(),title,type,schemaVersion:1,pinned:false,addedAt:Date.now(),updatedAt:Date.now()},index);}
function findShown(){const filter=$('#kind').value,q=$('#search').value.trim().toLowerCase();return objects.filter(object=> (filter==='archived'?object.archived:!object.archived)&& (['all','archived'].includes(filter)|| (filter==='pinned'?object.pinned:filter==='connected'?relationIds(object).length>0:filter==='files'?object.attachmentIds.length>0:object.type===filter)) && [object.title,object.content,object.url,...object.tags].join(' ').toLowerCase().includes(q));}
function cameraUpdate(){world.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.scale})`;$('#zoom-label').textContent=Math.round(camera.scale*100)+'%';}
function fit(){shown=findShown();if(!shown.length)return;const xs=shown.map(o=>o.position.x),ys=shown.map(o=>o.position.y);const minX=Math.min(...xs),minY=Math.min(...ys),width=Math.max(...xs)+228-minX,height=Math.max(...ys)+190-minY;camera.scale=Math.min(1.25,Math.max(.18,Math.min((board.clientWidth-48)/width,(board.clientHeight-48)/height)));camera.x=(board.clientWidth-width*camera.scale)/2-minX*camera.scale;camera.y=(board.clientHeight-height*camera.scale)/2-minY*camera.scale;cameraUpdate();}
function zoom(factor,x=board.clientWidth/2,y=board.clientHeight/2){const scale=Math.min(2,Math.max(.18,camera.scale*factor));camera.x=x-(x-camera.x)*scale/camera.scale;camera.y=y-(y-camera.y)*scale/camera.scale;camera.scale=scale;cameraUpdate();}
function edges(){const svg=$('#edges');svg.replaceChildren();const visible=new Set(shown.map(o=>o.id)),seen=new Set();for(const object of shown)for(const id of relationIds(object)){if(!visible.has(id))continue;const key=[object.id,id].sort().join('|');if(seen.has(key))continue;seen.add(key);const other=item(id),a=object.position,b=other.position;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${a.x+114} ${a.y+95} C ${a.x+114} ${(a.y+b.y)/2+95}, ${b.x+114} ${(a.y+b.y)/2+95}, ${b.x+114} ${b.y+95}`);if([object.id,id].includes(selectedId))path.classList.add('selected-edge');svg.append(path);}}
function render(){urls.forEach(URL.revokeObjectURL);urls=[];shown=findShown();$('#cards').replaceChildren();const live=active();$('#total').textContent=live.length;$('#prompts').textContent=live.filter(o=>o.type==='prompt').length;$('#connected').textContent=live.filter(o=>relationIds(o).length).length;$('#files').textContent=live.filter(o=>o.attachmentIds.length).length;$('#board-summary').textContent=`${shown.length} of ${live.length} active cards · select a card to edit and connect`;document.querySelectorAll('[data-filter]').forEach(button=>{const selected=button.dataset.filter===$('#kind').value;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected));});$('#empty').hidden=shown.length>0;$('#empty h3').textContent=live.length?'No cards match this view.':'Your first connection starts with a card.';$('#empty p').textContent=live.length?'Clear your search or choose All cards.':'Add a prompt, idea or image. Connect it to a reference to build context.';
 for(const object of shown){const card=el('article','board-card');card.dataset.id=object.id;card.dataset.type=object.type;card.classList.toggle('selected',object.id===selectedId);card.style.left=object.position.x+'px';card.style.top=object.position.y+'px';const top=el('div','card-top');top.append(el('span','',object.type.toUpperCase()+(object.pinned?' · PINNED':'')));const grip=el('button','grip','⠿');grip.setAttribute('aria-label','Move '+object.title);grip.title='Drag to move; arrow keys also move this card';bindDrag(grip,card,object);top.append(grip);const open=el('button','card-open');open.setAttribute('aria-label','Open '+object.title);open.append(el('h3','',object.title));const image=attachments.find(a=>object.attachmentIds.includes(a.id)&&['image/png','image/jpeg','image/webp','image/gif'].includes(a.type));if(image){const img=el('img');img.src=keepUrl(image.blob);img.alt=image.name;open.append(img);}else open.append(el('p','',object.content||object.url||'Select to add content and references.'));const foot=el('div','card-foot');foot.append(el('span','card-tags',object.tags.join(' · ')||'No tags'),el('span','card-count',`${relationIds(object).length} links${object.attachmentIds.length?' · '+object.attachmentIds.length+' files':''}`));open.append(foot);open.addEventListener('click',()=>select(object.id));card.append(top,open);$('#cards').append(card);}
 edges();cameraUpdate();$('#resume').hidden=!lastId||!item(lastId)||item(lastId).archived;if(selectedId)renderReferences();}
function canLeave(){return !dirty||confirm('Discard unsaved edits to this card?');}
function select(id){if(!canLeave())return;selectedId=id;dirty=false;const object=item(id);if(!object)return;lastId=id;writeMeta('last-card',id).catch(()=>{});$('.studio').classList.add('has-selection');$('#inspector-empty').hidden=true;$('#inspector-content').hidden=false;for(const field of ['title','type','content','url'])form.elements[field].value=object[field]||'';form.elements.tags.value=object.tags.join(', ');form.elements.pinned.checked=!!object.pinned;$('#selected-type').textContent=object.type.toUpperCase();$('#copy').textContent=object.type==='prompt'?'Copy prompt':'Copy content';$('#edit-status').textContent='Saved on this device';$('#archive').textContent=object.archived?'Restore card':'Archive card';$('#updated').textContent='Edited '+new Date(object.updatedAt).toLocaleDateString();$('#inspector').scrollTop=0;render();}
function close(){if(!canLeave())return;selectedId=null;dirty=false;$('.studio').classList.remove('has-selection');$('#inspector-empty').hidden=false;$('#inspector-content').hidden=true;render();}
function renderReferences(){const object=item(selectedId);if(!object)return;const list=$('#attachment-list');list.replaceChildren();if(!object.attachmentIds.length)list.append(el('p','hint','Attach a screenshot, image or file to keep it with this card.'));for(const id of object.attachmentIds){const file=attachments.find(a=>a.id===id);if(!file)continue;const wrapper=el('div','attachment');if(['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){const img=el('img');img.src=keepUrl(file.blob);img.alt=file.name;wrapper.append(img);}const row=el('div','attachment-bottom'),link=el('a','',file.name);link.href=keepUrl(file.blob);link.download=file.name;row.append(link,el('small','',Math.ceil(file.blob.size/1024)+' KB'));wrapper.append(row);list.append(wrapper);}
 const related=$('#related');related.replaceChildren();const ids=relationIds(object);if(!ids.length)related.append(el('p','hint','Connect a reference below. Its content will appear here beside your prompt.'));if(safeUrl(object.url)){const a=el('a','reference-link','Open reference link ↗');a.href=safeUrl(object.url);a.target='_blank';a.rel='noopener noreferrer';related.append(a);}for(const id of ids){const other=item(id),box=el('div','related-item'),top=el('div','related-top'),open=el('button','',other.title);open.addEventListener('click',()=>select(id));const unlink=el('button','','×');unlink.setAttribute('aria-label','Disconnect '+other.title);unlink.addEventListener('click',()=>connect(id,false));top.append(open,unlink);box.append(top);if(other.content)box.append(el('p','',other.content));if(safeUrl(other.url)){const a=el('a','','Open link ↗');a.href=safeUrl(other.url);a.target='_blank';a.rel='noopener noreferrer';box.append(a);}const image=attachments.find(a=>other.attachmentIds.includes(a.id)&&['image/png','image/jpeg','image/webp','image/gif'].includes(a.type));if(image){const img=el('img');img.src=keepUrl(image.blob);img.alt=image.name;box.append(img);}related.append(box);}
 const target=$('#connect-target');target.replaceChildren();const options=active().filter(o=>o.id!==selectedId&&!ids.includes(o.id));const empty=el('option','',options.length?'Choose a reference…':'Add another card first');empty.value='';target.append(empty);for(const option of options){const node=el('option','',option.title);node.value=option.id;target.append(node);}$('#connect').disabled=!options.length;}
async function commit(updated,files=[]){await saveBundle(updated,files);for(const object of updated){const index=objects.findIndex(o=>o.id===object.id);if(index<0)objects.push(object);else objects[index]=object;}for(const file of files){const index=attachments.findIndex(a=>a.id===file.id);if(index<0)attachments.push(file);else attachments[index]=file;}render();}
async function connect(id,enabled=true){if(busy)return;const a=item(selectedId),b=item(id);if(!a||!b||a.id===b.id)return;busy=true;try{await commit([a,b].map((o,index)=>({...o,relationships:enabled?[...new Set([...o.relationships,(index?a:b).id])]:o.relationships.filter(key=>key!==(index?a:b).id),updatedAt:Date.now()})));toast(enabled?'Cards connected. Reference is visible beside your content.':'Connection removed.');}catch(error){toast('Could not update connection: '+error.message);}finally{busy=false;}}
form.addEventListener('input',()=>{dirty=true;$('#edit-status').textContent='Unsaved changes';});form.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const object=item(selectedId);if(!object)return;const title=form.elements.title.value.trim(),url=form.elements.url.value.trim();if(!title||url&&!safeUrl(url)){$('#edit-status').textContent=!title?'Add a title.':'Use an http:// or https:// link.';return;}busy=true;$('#save').disabled=true;try{await commit([{...object,title,type:form.elements.type.value,content:form.elements.content.value,url,tags:[...new Set(form.elements.tags.value.split(',').map(t=>t.trim()).filter(Boolean))],pinned:form.elements.pinned.checked,updatedAt:Date.now()}]);dirty=false;$('#edit-status').textContent='Saved on this device';$('#selected-type').textContent=form.elements.type.value.toUpperCase();$('#copy').textContent=form.elements.type.value==='prompt'?'Copy prompt':'Copy content';toast('Changes saved.');}catch(error){$('#edit-status').textContent='Save failed: '+error.message;}finally{busy=false;$('#save').disabled=false;}});
$('#copy').addEventListener('click',async()=>{const text=form.elements.content.value||form.elements.url.value;if(!text){toast('Add content before copying.');return;}try{await navigator.clipboard.writeText(text);toast(form.elements.type.value==='prompt'?'Prompt copied. Paste it into your AI app.':'Content copied.');}catch{form.elements.content.focus();form.elements.content.select();toast('Select the content and use your device’s copy command.');}});
function add(){if(!canLeave())return;$('#new-form').reset();$('#new-error').textContent='';$('#new-dialog').showModal();$('#new-form').elements.title.focus();}
$('#add').addEventListener('click',add);$('#empty-add').addEventListener('click',add);$('#cancel-new').addEventListener('click',()=>$('#new-dialog').close());$('#new-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const title=event.target.elements.title.value.trim();if(!title)return;busy=true;try{const object=newObject(title,event.target.elements.type.value);await commit([object]);$('#kind').value='all';$('#search').value='';$('#new-dialog').close();dirty=false;select(object.id);fit();}catch(error){$('#new-error').textContent='Could not save: '+error.message;}finally{busy=false;}});
$('#close-inspector').addEventListener('click',close);$('#resume').addEventListener('click',()=>select(lastId));$('#connect').addEventListener('click',()=>connect($('#connect-target').value));$('#archive').addEventListener('click',async()=>{if(busy||!canLeave())return;const object=item(selectedId);busy=true;try{await commit([{...object,archived:!object.archived,updatedAt:Date.now()}]);dirty=false;selectedId=null;close();toast(object.archived?'Card restored.':'Card archived. Find it under Archived to restore it.');}catch(error){toast('Could not archive: '+error.message);}finally{busy=false;}});
$('#attach').addEventListener('click',()=>$('#attach-files').click());$('#attach-files').addEventListener('change',async event=>{const ownerId=selectedId;const files=[...event.target.files];event.target.value='';if(!ownerId||!files.length||busy)return;if(files.some(file=>file.size>20*1024*1024)||files.reduce((n,f)=>n+f.size,0)>50*1024*1024){toast('Use files under 20 MB each and batches under 50 MB.');return;}busy=true;$('#attach').disabled=true;try{const added=files.map(file=>({id:crypto.randomUUID(),name:file.name,type:file.type,blob:file,addedAt:Date.now()}));const owner=item(ownerId);await commit([{...owner,attachmentIds:[...owner.attachmentIds,...added.map(file=>file.id)],updatedAt:Date.now()}],added);toast('Files saved on this device.');}catch(error){toast('Attachment save failed: '+error.message);}finally{busy=false;$('#attach').disabled=false;}});
$('#search').addEventListener('input',()=>{render();if(mode==='board')fit();});$('#kind').addEventListener('change',()=>{render();fit();});document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{$('#kind').value=button.dataset.filter;$('#search').value='';render();fit();}));
function setMode(value){mode=value;board.classList.toggle('list',value==='list');$('#zoom-controls').hidden=value==='list';$('#gesture-help').textContent=value==='list'?'Select a card to work with it.':'Drag a card’s grip to move it. Drag the background to explore.';for(const name of ['board','list']){$('#'+name+'-mode').classList.toggle('active',name===value);$('#'+name+'-mode').setAttribute('aria-pressed',String(name===value));}render();if(value==='board')fit();}
$('#board-mode').addEventListener('click',()=>setMode('board'));$('#list-mode').addEventListener('click',()=>setMode('list'));$('#zoom-out').addEventListener('click',()=>zoom(.8));$('#zoom-in').addEventListener('click',()=>zoom(1.25));$('#fit').addEventListener('click',fit);
function bindDrag(grip,card,object){let drag;grip.addEventListener('pointerdown',event=>{if(mode==='list'||busy)return;event.preventDefault();event.stopPropagation();grip.setPointerCapture(event.pointerId);drag={x:event.clientX,y:event.clientY,origin:{...object.position}};});grip.addEventListener('pointermove',event=>{if(!drag)return;object.position={x:Math.max(0,drag.origin.x+(event.clientX-drag.x)/camera.scale),y:Math.max(0,drag.origin.y+(event.clientY-drag.y)/camera.scale)};card.style.left=object.position.x+'px';card.style.top=object.position.y+'px';edges();});const end=async()=>{if(!drag)return;const origin=drag.origin;drag=null;try{await saveBundle([{...object,layoutVersion:2}]);}catch(error){object.position=origin;render();toast('Position save failed: '+error.message);}};grip.addEventListener('pointerup',end);grip.addEventListener('pointercancel',end);grip.addEventListener('keydown',async event=>{const offsets={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};if(!offsets[event.key]||busy)return;event.preventDefault();const [x,y]=offsets[event.key];const old={...object.position};object.position={x:Math.max(0,old.x+x),y:Math.max(0,old.y+y)};card.style.left=object.position.x+'px';card.style.top=object.position.y+'px';edges();try{await saveBundle([object]);}catch{object.position=old;render();toast('Position could not be saved.');}});}
let pointers=new Map(),pan=null,pinch=null;board.addEventListener('pointerdown',event=>{if(mode==='list'||event.target.closest('button,.board-card'))return;board.setPointerCapture(event.pointerId);pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});pan={x:event.clientX,y:event.clientY,origin:{...camera}};if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y)};pan=null;}});board.addEventListener('pointermove',event=>{if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===2&&pinch){const [a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),rect=board.getBoundingClientRect();zoom(distance/Math.max(1,pinch.distance),(a.x+b.x)/2-rect.left,(a.y+b.y)/2-rect.top);pinch.distance=distance;}else if(pan){camera.x=pan.origin.x+event.clientX-pan.x;camera.y=pan.origin.y+event.clientY-pan.y;cameraUpdate();}});for(const eventName of ['pointerup','pointercancel'])board.addEventListener(eventName,event=>{pointers.delete(event.pointerId);pan=null;pinch=null;});board.addEventListener('wheel',event=>{if(mode==='list')return;event.preventDefault();const rect=board.getBoundingClientRect();zoom(Math.exp(-event.deltaY*.0015),event.clientX-rect.left,event.clientY-rect.top);},{passive:false});
$('#example').addEventListener('click',async()=>{if(busy||!canLeave())return;const existing=objects.find(o=>o.exampleGroup==='starter'&&!o.archived);if(existing){$('#kind').value='all';$('#search').value='';dirty=false;select(existing.id);fit();return;}busy=true;try{const prompt=newObject('Design a focused AI workspace','prompt'),brief=newObject('What makes it useful?','note'),style=newObject('Visual direction','note'),ref=newObject('Interaction reference','link');prompt.content='Design a personal AI workspace that helps me turn references into reusable prompts. Use the connected brief and visual direction. Show one focused layout with a working board, a prompt editor and related references. Explain each interaction clearly. Avoid decorative features that do nothing.';brief.content='Every control must do something useful. Keep a prompt and its source material visible together. Save work locally. Make capture quick on the phone and editing spacious on desktop.';style.content='Dark graphite background. Restrained violet accents. Generous spacing. Strong readable type. Cards use subtle type-specific colors. Prioritize content over decoration.';ref.url='https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events';ref.content='A technical reference for mouse, touch and pen interactions on a visual board.';const baseY=active().length?Math.max(...active().map(o=>o.position.y))+245:0;prompt.position={x:350,y:baseY+150};brief.position={x:40,y:baseY+20};style.position={x:40,y:baseY+275};ref.position={x:650,y:baseY+150};prompt.relationships=[brief.id,style.id,ref.id];for(const object of [prompt,brief,style,ref]){object.tags=['example'];object.exampleGroup='starter';}await commit([prompt,brief,style,ref]);$('#kind').value='all';$('#search').value='';dirty=false;select(prompt.id);fit();toast('Example board added. Edit the prompt with its references beside it.');}catch(error){toast('Example could not be saved: '+error.message);}finally{busy=false;}});
const readBlob = blob => new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});
$('#backup').addEventListener('click',async()=>{if(busy)return;try{const files=await Promise.all(attachments.map(async file=>({id:file.id,name:file.name,type:file.type,addedAt:file.addedAt,data:await readBlob(file.blob)})));const blob=new Blob([JSON.stringify({schemaVersion:2,exportedAt:new Date().toISOString(),objects,attachments:files,metadata:(await listMeta()).filter(record=>!['firebase-config','supabase-config','sync-owner'].includes(record.key))},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='NEXUS-TK54-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup includes cards, connections and attached files.');}catch(error){toast('Backup failed: '+error.message);}});
$('#restore').addEventListener('click',()=>$('#restore-file').click());$('#restore-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file||busy||!canLeave())return;busy=true;try{const backup=JSON.parse(await file.text());if(![1,2].includes(backup.schemaVersion)||!Array.isArray(backup.objects)||backup.objects.length>10000)throw new Error('Unsupported backup format.');const allowed=['note','prompt','link','image'];const restored=backup.objects.map((object,i)=>{if(typeof object.id!=='string'||typeof object.title!=='string'||!allowed.includes(object.type)||!Array.isArray(object.tags)||object.tags.some(t=>typeof t!=='string')||typeof object.content!=='string'||object.relationships&&(!Array.isArray(object.relationships)||object.relationships.some(id=>typeof id!=='string'))||object.attachmentIds&&(!Array.isArray(object.attachmentIds)||object.attachmentIds.some(id=>typeof id!=='string')))throw new Error('Invalid card data.');const normalized=normalize(object,i);if(!Number.isFinite(normalized.position?.x)||!Number.isFinite(normalized.position?.y))throw new Error('Invalid card position.');if(normalized.url&&!safeUrl(normalized.url))throw new Error('Unsafe reference link.');return normalized;});if(new Set(restored.map(o=>o.id)).size!==restored.length)throw new Error('Duplicate card IDs.');const files=(backup.attachments||[]).map(file=>{if(typeof file.id!=='string'||typeof file.name!=='string'||typeof file.type!=='string'||typeof file.data!=='string'||!/^data:[^,]*;base64,/.test(file.data))throw new Error('Invalid attachment.');const bytes=Uint8Array.from(atob(file.data.split(',')[1]),c=>c.charCodeAt(0));return{id:file.id,name:file.name,type:file.type,addedAt:file.addedAt,blob:new Blob([bytes],{type:file.type})};});if(!confirm('Merge this backup into your studio? Cards with matching IDs will be replaced.'))return;if(backup.metadata&&!Array.isArray(backup.metadata))throw new Error('Invalid studio metadata.');const allowedKeys=['dna-profiles','dna-draft','workflow-draft','workflows','run-history','last-card'];const meta=(backup.metadata||[]).filter(record=>record&&allowedKeys.includes(record.key));await commit(restored,files);for(const record of meta)await saveMeta(record);window.dispatchEvent(new Event('studio:refresh'));dirty=false;if(selectedId)select(selectedId);fit();toast('Backup restored.');}catch(error){toast('Restore failed: '+error.message);}finally{busy=false;}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#install').hidden=false;});$('#install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}});
try{objects=(await listObjects()).map(normalize);attachments=await listAttachments();lastId=(await readMeta('last-card'))?.value;$('#storage-status').textContent='● Saved on this device';await saveBundle(objects);render();setMode(matchMedia('(max-width:760px)').matches?'list':'board');}catch(error){$('#storage-status').textContent='Storage unavailable';$('#add').disabled=true;toast('Could not open local storage: '+error.message);}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>toast('Offline app loading could not be enabled.'));

window.addEventListener('studio:refresh',async()=>{objects=(await listObjects()).map(normalize);attachments=await listAttachments();render();});
window.addEventListener('studio:open-card',event=>{if(item(event.detail))select(event.detail);});
for(const page of ['dna','logic']){const sendButton=el('button','',page==='dna'?'Explore in Design DNA':'Use in Logic Studio');sendButton.addEventListener('click',()=>{if(!canLeave())return;dirty=false;window.dispatchEvent(new CustomEvent('studio:send',{detail:{id:selectedId,page}}));});let actions=document.querySelector('.send-actions');if(!actions){actions=el('div','send-actions');document.querySelector('#inspector-content').insertBefore(actions,document.querySelector('#edit-form'));}actions.append(sendButton);}
